--
-- Unité Expérimentale de Lexicosynthèse (...)
--

--
-- Les prefixes
--
drop table prefixes;
create table prefixes (
  prefixe  text,
  signifie text
);

insert into prefixes values ('ACRO','L\'EXTREMITE');
insert into prefixes values ('ADENO','LA GLANDE');
insert into prefixes values ('AERO','L\'AIR');
insert into prefixes values ('AGRO','LE CHAMP');
insert into prefixes values ('ALGO','LA DOULEUR');
insert into prefixes values ('ALLO','L\'AUTRE');
insert into prefixes values ('ANDRO','L\'HOMME');
insert into prefixes values ('ARCHEO','L\'ANCIEN');
insert into prefixes values ('ARITHMO','LE NOMBRE');
insert into prefixes values ('ARRHENO','LE MALE');
insert into prefixes values ('ARSENO','LA VIRILITE');
insert into prefixes values ('ANISO','INEGAL');
insert into prefixes values ('ANTE','L\'AVANT');
insert into prefixes values ('ANTI','LE CONTRAIRE');
insert into prefixes values ('ANTHO','LA FLEUR');
insert into prefixes values ('ARTERIO','L\'ARTERE');
insert into prefixes values ('ARTHRO','L\'ARTICULATION');
insert into prefixes values ('APO','A PARTIR DE');
insert into prefixes values ('ASTERO','L\'ETOILE');
insert into prefixes values ('ASTRO','L\'ASTRE');
insert into prefixes values ('ASTHENO','LA FATIGUE');
insert into prefixes values ('ANTHROPO','L\'HOMME');
insert into prefixes values ('APHRO','LA MOUSSE');
insert into prefixes values ('ARCHEO','L\'ANCIEN');
insert into prefixes values ('ARGO','LE BRILLANT');
insert into prefixes values ('AUTO','SOI-MEME');
insert into prefixes values ('BACTERIO','LA BACTERIE');
insert into prefixes values ('BALANO','LA GLANDE');
insert into prefixes values ('BARO','LA PESANTEUR');
insert into prefixes values ('BARO','LA PRESSION');
insert into prefixes values ('BARY','LOURD(E)');
insert into prefixes values ('BATHY','PROFOND(E)');
insert into prefixes values ('BI','(Double)');
insert into prefixes values ('BIBLIO','LE LIVRE');
insert into prefixes values ('BIDULO','LE MACHIN');
insert into prefixes values ('BIO','LA VIE');
insert into prefixes values ('BLENO','LE MUCUS');
insert into prefixes values ('BLASTO','LE GERME');
insert into prefixes values ('BOLO','LE JET');
insert into prefixes values ('BRACHY','COURT(E)');
insert into prefixes values ('BRADY','LENT(E)');
insert into prefixes values ('BRONCHO','LA BRONCHE');
insert into prefixes values ('BRONTO','LE TONNERRE');
insert into prefixes values ('BUTYRO','LE BEURRE');
insert into prefixes values ('CACO','MAUVAIS(E)');
insert into prefixes values ('CALLI','BEAU(BELLE)');
insert into prefixes values ('CARDIO','LE COEUR');
insert into prefixes values ('CARYO','LA NOIX');
insert into prefixes values ('CATA','(Sur)');
insert into prefixes values ('CENTRO','LE CENTRE');
insert into prefixes values ('CERCO','LA QUEUE');
insert into prefixes values ('CINEMATO','LE MOUVEMENT');
insert into prefixes values ('CLEPTO','LE VOL');
insert into prefixes values ('CLIMATO','LA REGION');
insert into prefixes values ('CLINO','L\'INCLINAISON');
insert into prefixes values ('CENO','LE VIDE');
insert into prefixes values ('CEPHALO','LA TETE');
insert into prefixes values ('CERATO','LA CORNE');
insert into prefixes values ('CHERIO','LA MAIN');
insert into prefixes values ('CHELI','LA PINCE');
insert into prefixes values ('CHETO','LA CRINIERE');
insert into prefixes values ('CHIMIO','LA CHIMIE');
insert into prefixes values ('CHLORO','LE JAUNE');
insert into prefixes values ('CHRYSO','L\'OR');
insert into prefixes values ('CHROMO','LA DOULEUR');
insert into prefixes values ('CHRONO','LE TEMPS');
insert into prefixes values ('CO','(Avec)');
insert into prefixes values ('COLEO','CREUX(SE)');
insert into prefixes values ('COPRO','L\'EXCREMENT');
insert into prefixes values ('CONTRA','(Contre)');
insert into prefixes values ('COSMO','LE COSMOS');
insert into prefixes values ('CRANIO','LE CRANE');
insert into prefixes values ('CRISTALLO','LE VERRE');
insert into prefixes values ('CRYO','LE FROID');
insert into prefixes values ('CRYPTO','CACHE(E)');
insert into prefixes values ('CYANO','LE BLEU');
insert into prefixes values ('CYCLO','LE CERCLE');
insert into prefixes values ('CYNO','LE CHIEN');
insert into prefixes values ('CYPHO','CONVEXE');
insert into prefixes values ('CYTO','LA CELLULE');
insert into prefixes values ('DACTYLO','LE DOIGT');
insert into prefixes values ('DECI','(Un dixieme)');
insert into prefixes values ('DERMATO','LA PEAU');
insert into prefixes values ('DI','(Double)');
insert into prefixes values ('DIA','(A travers)');
insert into prefixes values ('DIPLO','(Double)');
insert into prefixes values ('DINO','TERRIBLE');
insert into prefixes values ('DECA','(Dix)');
insert into prefixes values ('DEMO','LE PEUPLE');
insert into prefixes values ('DEMONO','LE DIABLE');
insert into prefixes values ('DENDRO','L\'ARBRE');
insert into prefixes values ('DERMO','LA PEAU');
insert into prefixes values ('DEUTERO','LE SECOND');
insert into prefixes values ('DEXTRO','DROIT(E)');
insert into prefixes values ('DODECA','(Douze)');
insert into prefixes values ('DOXO','L\'OPINION');
insert into prefixes values ('DRAMA','LE THEATRE');
insert into prefixes values ('DROMO','LA COURSE');
insert into prefixes values ('DYNAMO','L\'ENERGIE');
insert into prefixes values ('DYS','LA DIFFICULTE');
insert into prefixes values ('ECTO','L\'INTERIEUR');
insert into prefixes values ('ELASTO','L\'ELASTIQUE');
insert into prefixes values ('ELECTRO','L\'ELECTRICITE');
insert into prefixes values ('EMBYO','L\'EMBRYON');
insert into prefixes values ('ENCEPHALO','LE CERVEAU');
insert into prefixes values ('ENDO','L\'INTERIEUR');
insert into prefixes values ('ENTERO','LES ENTRAILLES');
insert into prefixes values ('ENTOMO','L\'INSECTE');
insert into prefixes values ('EO','L\'AURORE');
insert into prefixes values ('EPI','(Sur)');
insert into prefixes values ('EPISTEMO','LA SCIENCE');
insert into prefixes values ('ERGO','LE TRAVAIL');
insert into prefixes values ('ESTHETICO','L\'ESTHETIQUE');
insert into prefixes values ('EROTICO','L\'EROTISME');
insert into prefixes values ('ETHYMO','LA VERITE');
insert into prefixes values ('EU','(Bien)');
insert into prefixes values ('EXO','(Dehors)');
insert into prefixes values ('FANTASMO','L\'ILLUSION');
insert into prefixes values ('FIBRO','LA FIBRE');
insert into prefixes values ('GALACTO','LE LAIT');
insert into prefixes values ('GAMO','LE MARIAGE');
insert into prefixes values ('GASTRO','LE VENTRE');
insert into prefixes values ('GEO','LA TERRE');
insert into prefixes values ('GERONTO','LE VIEILLARD');
insert into prefixes values ('GENO','LA RACE');
insert into prefixes values ('GLOSO','LA LANGUE');
insert into prefixes values ('GLYCO','LE SUCRE');
insert into prefixes values ('GNOSEO','LA CONNAISSANCE');
insert into prefixes values ('GONIO','L\'ANGLE');
insert into prefixes values ('GONO','LA SEMENCE');
insert into prefixes values ('GRAMMO','LE MESSAGE');
insert into prefixes values ('GRAPHO','L\'ECRITURE');
insert into prefixes values ('GRAVITO','LA GRAVITE');
insert into prefixes values ('GYMNO','NU(E)');
insert into prefixes values ('GYNO','LA FEMME');
insert into prefixes values ('GYRO','LE CERCLE');
insert into prefixes values ('HALO','LE SEL');
insert into prefixes values ('HECTO','(Cent)');
insert into prefixes values ('HELIO','LE SOLEIL');
insert into prefixes values ('HEMATO','LE SANG');
insert into prefixes values ('HEMI','LA MOITIE');
insert into prefixes values ('HEPATO','LE FOIE');
insert into prefixes values ('HEPTA','(Sept)');
insert into prefixes values ('HETERO','L\'AUTRE');
insert into prefixes values ('HEXA','(Six)');
insert into prefixes values ('HIERO','SACRE(E)');
insert into prefixes values ('HIPPO','LE CHEVAL');
insert into prefixes values ('HISTO','LE TISSU');
insert into prefixes values ('HODO','LE CHEMIN');
insert into prefixes values ('HOLO','ENTIER(E)');
insert into prefixes values ('HOMEO','SEMBLABLE');
insert into prefixes values ('HOMO','SEMBLABLE');
insert into prefixes values ('HYDRO','L\'EAU');
insert into prefixes values ('HYGRO','L\'HUMIDITE');
insert into prefixes values ('HYLO','LA MATIERE');
insert into prefixes values ('HYMENO','LA MEMBRANE');
insert into prefixes values ('HYPER','(Au Delà de)');
insert into prefixes values ('HYPHO','LE TISSU');
insert into prefixes values ('HYPO','L\'INSUFFISANCE');
insert into prefixes values ('HYSTERO','L\'UTERUS');
insert into prefixes values ('ICHTYO','LE POISSON');
insert into prefixes values ('ICONO','L\'IMAGE');
insert into prefixes values ('IDEO','L\'IDEE');
insert into prefixes values ('IDIO','PROPRE');
insert into prefixes values ('INFLATO','GONFLE(E)');
insert into prefixes values ('INFRA','(En dessous)');
insert into prefixes values ('ISO','EGAL(E)');
insert into prefixes values ('INTRA','(En dedans)');
insert into prefixes values ('JUXTA','(A coté)');
insert into prefixes values ('KILO','(Mille)');
insert into prefixes values ('LATERO','LE COTE');
insert into prefixes values ('LARYNGO','LA GORGE');
insert into prefixes values ('LEPTO','MINCE');
insert into prefixes values ('LEVO','LA GAUCHE');
insert into prefixes values ('LIPO','LA GRAISSE');
insert into prefixes values ('LITHO','LA PIERRE');
insert into prefixes values ('LOGO','LE DISCOURS');
insert into prefixes values ('LOXO','OBLIQUE');
insert into prefixes values ('MACRO','GRAND(E)');
insert into prefixes values ('MAGNETO','LE MAGNETISME');
insert into prefixes values ('MASTO','LA MAMELLE');
insert into prefixes values ('MEGA','GRAND(E)');
insert into prefixes values ('MEGALO','GRAND(E)');
insert into prefixes values ('MELO','LE CHANT');
insert into prefixes values ('MERO','(Une partie)');
insert into prefixes values ('MESO','LE MILIEU');
insert into prefixes values ('METEO','LES AIRS');
insert into prefixes values ('META','LE CHANGEMENT');
insert into prefixes values ('METRO','LA MESURE');
insert into prefixes values ('MICRO','PETIT(E)');
insert into prefixes values ('MISO','LA HAINE');
insert into prefixes values ('MNEMO','LA MEMOIRE');
insert into prefixes values ('MORPHO','LA FORME');
insert into prefixes values ('MONO','SEUL(E)');
insert into prefixes values ('MULTI','MULTIPLE');
insert into prefixes values ('MYCO','LE CHAMPIGNON');
insert into prefixes values ('MYELO','LA MOELLE');
insert into prefixes values ('MYO','LE MUSCLE');
insert into prefixes values ('MYTHO','LE MYTHE');
insert into prefixes values ('NANO','LE NAIN');
insert into prefixes values ('NECRO','LA MORT');
insert into prefixes values ('NEO','NOUVEAU(ELLE)');
insert into prefixes values ('NEURO','LE NERF');
insert into prefixes values ('NEMATO','LE FIL');
insert into prefixes values ('NEPHRO','LE REIN');
insert into prefixes values ('NEVRO','LE NERF');
insert into prefixes values ('NOO','L\'ESPRIT');
insert into prefixes values ('NOMO','LA LOI');
insert into prefixes values ('NOSO','LA MALADIE');
insert into prefixes values ('NYCTO','LA NUIT');
insert into prefixes values ('NUCLEO','LE NOYAU');
insert into prefixes values ('OCTO','(Huit)');
insert into prefixes values ('ODO','LA ROUTE');
insert into prefixes values ('OENO','LE VIN');
insert into prefixes values ('OLEO','L\'HUILE');
insert into prefixes values ('OLIGO','RARE');
insert into prefixes values ('OMNI','LE TOUT');
insert into prefixes values ('ONTO','L\'ETRE');
insert into prefixes values ('OVO','L\'OEUF');
insert into prefixes values ('OPHTALMO','L\'OEIL');
insert into prefixes values ('ORCHIDO','LE TESTICULE');
insert into prefixes values ('ORGANO','L\'ORGANE');
insert into prefixes values ('ORNITHO','L\'OISEAU');
insert into prefixes values ('ORO','LA MONTAGNE');
insert into prefixes values ('ORTHO','LE DROIT');
insert into prefixes values ('OSCILLO','L\'OSCILLATION');
insert into prefixes values ('OSMO','LA PULSION');
insert into prefixes values ('OTO','L\'OREILLE');
insert into prefixes values ('PACHY','EPAIS(SE)');
insert into prefixes values ('PALEO','ANCIEN(NE)');
insert into prefixes values ('PALIN','EN ARRIERE');
insert into prefixes values ('PAN','LE TOUT');
insert into prefixes values ('PANTO','LE TOUT');
insert into prefixes values ('PARA','(Opposé à)');
insert into prefixes values ('PAPYRO','LE PAPIER');
insert into prefixes values ('PARALLELO','PARALLELE');
insert into prefixes values ('PATA','LA PATATE');
insert into prefixes values ('PATHO','LA SOUFFRANCE');
insert into prefixes values ('PEDO','LE PIED');
insert into prefixes values ('PEDO','LE SOL');
insert into prefixes values ('PENTA','(Cinq)');
insert into prefixes values ('PERI','(Autours de)');
insert into prefixes values ('PETRO','LA PIERRE');
insert into prefixes values ('PHAGO','MANGEUR(EUSE)');
insert into prefixes values ('PHALLO','LE SEXE');
insert into prefixes values ('PHANERO','VISIBLE');
insert into prefixes values ('PHARMACO','LE MEDICAMENT');
insert into prefixes values ('PHARYNGO','LE GOSIER');
insert into prefixes values ('PHENO','L\'APPARITION');
insert into prefixes values ('PHILO','L\'AMOUR');
insert into prefixes values ('PHYLO','LA FEUILLE');
insert into prefixes values ('PHOBO','LA PEUR');
insert into prefixes values ('PHONO','LE SON');
insert into prefixes values ('PHOTO','LA LUMIERE');
insert into prefixes values ('PHRENO','L\'ESPRIT');
insert into prefixes values ('PHYLO','LA RACE');
insert into prefixes values ('PHYSIO','LA NATURE');
insert into prefixes values ('PHYTO','LA PLANTE');
insert into prefixes values ('PINATO','LE TABLEAU');
insert into prefixes values ('PITHECO','LE SINGE');
insert into prefixes values ('PLASMO','LE FACONNAGE');
insert into prefixes values ('PLASTO','LE MODELAGE');
insert into prefixes values ('PLECTO','LA SOUDURE');
insert into prefixes values ('PLEO','(Plus)');
insert into prefixes values ('PLEISTO','(Beaucoup)');
insert into prefixes values ('PLESIO','PROCHE');
insert into prefixes values ('PLEURO','(A coté)');
insert into prefixes values ('PLOUTO','RICHE');
insert into prefixes values ('PLURI','PLUSIEUR');
insert into prefixes values ('POLEMO','LE GUERRE');
insert into prefixes values ('PNEUMO','LE POUMON');
insert into prefixes values ('PODO','LE PIED');
insert into prefixes values ('POLY','(Nombreux)');
insert into prefixes values ('PORNO','LE COCHON');
insert into prefixes values ('POST','(Après)');
insert into prefixes values ('PRIMO','LE PREMIER');
insert into prefixes values ('PRO','(Pour)');
insert into prefixes values ('PROTO','LE PREMIER');
insert into prefixes values ('PSEUDO','LE FAUX');
insert into prefixes values ('PSYCHO','L\'AME');
insert into prefixes values ('PTERO','L\'AILE');
insert into prefixes values ('PYO','LE PUS');
insert into prefixes values ('PYRO','LE FEU');
insert into prefixes values ('QUADRI','(Quadruple)');
insert into prefixes values ('QUASI','(Presque)');
insert into prefixes values ('RADIO','LE RAYON');
insert into prefixes values ('REHO','COULER');
insert into prefixes values ('RETRO','L\'ARRIERE');
insert into prefixes values ('RHINO','LE NEZ');
insert into prefixes values ('RHIZO','LA RACINE');
insert into prefixes values ('RHOMBO','LE LOSANGE');
insert into prefixes values ('SCATO','L\'EXCREMENT');
insert into prefixes values ('SCLERO','(Dur)');
insert into prefixes values ('SELENO','LA LUNE');
insert into prefixes values ('SEMIO','LE SENS');
insert into prefixes values ('SEMA','LE SIGNE');
insert into prefixes values ('SEMI','(A Demi)');
insert into prefixes values ('SEXO','LE SEXE');
insert into prefixes values ('SCHISO','LA SEPARATION');
insert into prefixes values ('SIDERO','LE FER');
insert into prefixes values ('SIMILI','SEMBLABLE');
insert into prefixes values ('SOLENO','LE TUYAU');
insert into prefixes values ('SOMATO','LE CORPS');
insert into prefixes values ('SPHERO','LA SPHERE');
insert into prefixes values ('SPHENO','LE COIN');
insert into prefixes values ('SPLENO','LA RATE');
insert into prefixes values ('SPONDYLO','LA VERTEBRE');
insert into prefixes values ('STAPHILO','LE GRAIN');
insert into prefixes values ('STEGO','LE TOIT');
insert into prefixes values ('STENO','ETROIT(E)');
insert into prefixes values ('STEREO','LA SOLIDITE');
insert into prefixes values ('STERNO','LA POITRINE');
insert into prefixes values ('STATO','L\'IMMOBILITE');
insert into prefixes values ('STOMATO','LA BOUCHE');
insert into prefixes values ('STROBO','LE TOURBILLON');
insert into prefixes values ('STYLO','LA COLONNE');
insert into prefixes values ('TACHY','LA VITESSE');
insert into prefixes values ('TAUTO','LE MEME');
insert into prefixes values ('TAXO','L\'ORDRE');
insert into prefixes values ('TECHNO','L\'ART');
insert into prefixes values ('TELEO','LOIN DE');
insert into prefixes values ('TERATO','LE MONSTRE');
insert into prefixes values ('TETRA','(Quatre)');
insert into prefixes values ('THALASSO','LA MER');
insert into prefixes values ('THEO','LA DIVINITE');
insert into prefixes values ('THERMO','LA CHALEUR');
insert into prefixes values ('TOMO','COUPER');
insert into prefixes values ('TONI','LE TON');
insert into prefixes values ('TOPO','LE LIEU');
insert into prefixes values ('TYPO','LE CARACTERE');
insert into prefixes values ('TROPO','TENDANCE VERS');
insert into prefixes values ('TRI','(Triple)');
insert into prefixes values ('URANO','LE CIEL');
insert into prefixes values ('URO','L\'URINE');
insert into prefixes values ('XANTHO','LE JAUNE');
insert into prefixes values ('XENO','L\'ETRANGER');
insert into prefixes values ('XYLO','LE BOIS');
insert into prefixes values ('ZOO','L\'ANIMAL');
insert into prefixes values ('OSTEO','L\'OS');
insert into prefixes values ('SARCO','LA CHAIR');
insert into prefixes values ('STETHO','LA POITRINE');
insert into prefixes values ('TRACHEO','LA TRACHEE');

grant select on prefixes to public;

--
-- Les suffixes
--
drop table suffixes;
create table suffixes (
  suffixe  text,
  signifie text
);

insert into suffixes values ('ABLE','QUI PEUT ETRE');
insert into suffixes values ('ACRE','L\'EXTREMITE DE');
insert into suffixes values ('ACTION','LES EFFETS DE');
insert into suffixes values ('AGOGIE','CONDUISANT A');
insert into suffixes values ('AGOGUE','QUI CONDUIT');
insert into suffixes values ('AISE','ORIGINAIRE DE');
insert into suffixes values ('ASTRE','L\'ETOILE DE');
insert into suffixes values ('AISON','LES EFFETS DE');
insert into suffixes values ('ASTHENIE','LA FATIGUE DE');
insert into suffixes values ('AL','(Adjectif)');
insert into suffixes values ('ALE','(Adjectif)');
insert into suffixes values ('ALGIE','LA DOULEUR DE');
insert into suffixes values ('ANCE','LES EFFETS DE');
insert into suffixes values ('ANE','CARBURE SATURE DE');
insert into suffixes values ('ANTHROPE','L\'HOMME DE');
insert into suffixes values ('ARCHIE','LE COMMANDEMENT DE');
insert into suffixes values ('ARQUE','LE COMMANDANT DE');
insert into suffixes values ('ATE','LE SEL DE');
insert into suffixes values ('ATION','LES EFFETS DE');
insert into suffixes values ('ARGE','BRILLANT COMME');
insert into suffixes values ('BATHE','LA PROFONDEUR DE');
insert into suffixes values ('BIE','LA VIE DE');
insert into suffixes values ('CARDE','LE COEUR DE');
insert into suffixes values ('CARPE','LE FRUIT DE');
insert into suffixes values ('CENTRIQUE','CENTRE SUR');
insert into suffixes values ('CEPHALE','LA TETE DE');
insert into suffixes values ('CERE','LA CORNE DE');
insert into suffixes values ('CERQUE','LA QUEUE DE');
insert into suffixes values ('CHROME','LA COULEUR DE');
insert into suffixes values ('CHRONISME','LE TEMPS DE');
insert into suffixes values ('CHRONE','LE TEMPS DE');
insert into suffixes values ('CHTONE','LA TERRE DE');
insert into suffixes values ('CIDE','LE MEURTRE DE');
insert into suffixes values ('CINETIQUE','LE MOUVEMENT DE');
insert into suffixes values ('COLE','LA CULTURE DE');
insert into suffixes values ('CLASTE','BRISEUR DE');
insert into suffixes values ('COPE','LA COUPE DE');
insert into suffixes values ('COQUE','LA GRAINE DE');
insert into suffixes values ('COSME','LE MONDE DE');
insert into suffixes values ('CRATIE','LA FORCE DE');
insert into suffixes values ('CRETION','LA PRODUCTION DE');
insert into suffixes values ('CULTURE','LA CULTURE DE');
insert into suffixes values ('CURE','LE SOIN DE');
insert into suffixes values ('CYCLE','LA ROTATION DE');
insert into suffixes values ('CYTE','LA CELLULE DE');
insert into suffixes values ('DACTYLE','LE DOIGT DE');
insert into suffixes values ('DEMIE','LE PEUPLE DE');
insert into suffixes values ('DERME','LA PEAU DE');
insert into suffixes values ('DESE','LA REUNION DE');
insert into suffixes values ('DIDACTE','QUI INSTRUIT');
insert into suffixes values ('DI','LE JOUR DE');
insert into suffixes values ('DROME','TERRAIN DE COURSE DE');
insert into suffixes values ('DROMIE','LA COURSE DE');
insert into suffixes values ('DOXE','L\'OPINION DE');
insert into suffixes values ('DYNE','L\'ENERGIE DE');
insert into suffixes values ('EDRE','LA BASE DE');
insert into suffixes values ('EEN(NE)','ORIGINAIRE DE');
insert into suffixes values ('ELET(TE)','DIMINUTIF DE');
insert into suffixes values ('EMENT','A LA MANIERE DE');
insert into suffixes values ('ECTOMIE','L\'ABLATION DE');
insert into suffixes values ('EMIE','LE SANG DE');
insert into suffixes values ('ENE','CARBURE D\'HYDROGENE DE');
insert into suffixes values ('ERGIE','LE TRAVAIL DE');
insert into suffixes values ('ESQUE','LA RESSEMBLANCE DE');
insert into suffixes values ('ESTHESIE','LA SENSATION DE');
insert into suffixes values ('ESTRE','QUI VIENT DE');
insert into suffixes values ('ET(TE)','DIMINUTIF DE');
insert into suffixes values ('FERE','QUI PORTE DE');
insert into suffixes values ('FUGE','QUI FUIT');
insert into suffixes values ('GAME','QUI SE MARIE AVEC');
insert into suffixes values ('GAMIE','LE MARIAGE DE');
insert into suffixes values ('GASTRIQUE','QUI A LE VENTRE DE');
insert into suffixes values ('GEE','LA TERRE DE');
insert into suffixes values ('GENIQUE','QUI ENGENDRE');
insert into suffixes values ('GENE','QUI A LA FORME DE');
insert into suffixes values ('GENESE','LA FORMATION DE');
insert into suffixes values ('GLYPHE','LA GRAVURE DE');
insert into suffixes values ('GLOTTE','LA LANGUE DE');
insert into suffixes values ('GNATHE','LA MACHOIRE DE');
insert into suffixes values ('GRADE','QUI MARCHE SUR');
insert into suffixes values ('GRAMME','LE DESSIN DE');
insert into suffixes values ('GRAPHIE','L\'ETUDE GRAPHIQUE DE');
insert into suffixes values ('HELIE','(Soleil)');
insert into suffixes values ('HYDRE','L\'ETAT LIQUIDE DE');
insert into suffixes values ('HYDRIQUE','ACIDE NON OXYGENE DE');
insert into suffixes values ('IATRIE','LA MEDECINE DE');
insert into suffixes values ('IBLE','LA POSSIBILITE DE');
insert into suffixes values ('IDE','LA FAMILLE DE');
insert into suffixes values ('ITE','L\' INFLAMMATION DE');
insert into suffixes values ('IFIER','FAIRE');
insert into suffixes values ('ILLON','DIMINUTIF DE');
insert into suffixes values ('ING','ACTION DE');
insert into suffixes values ('LABIAL','QUI A LES LEVRES DE');
insert into suffixes values ('LACRYMAL','QUI A LES LARMES DE');
insert into suffixes values ('LATERE','LE COTE DE');
insert into suffixes values ('LATRIE','L\'ADORATION DE');
insert into suffixes values ('LOGIE','L\'ETUDE DE');
insert into suffixes values ('LYSE','DISSOLUTION DE');
insert into suffixes values ('LITHE','LA PIERRE DE');
insert into suffixes values ('LOGUE','SPECIALISTE DE');
insert into suffixes values ('MACHIE','LE COMBAT DE');
insert into suffixes values ('MANCIE','PREDICTION DE L\'AVENIR PAR');
insert into suffixes values ('MANIE','LA FOLIE DE');
insert into suffixes values ('MASTOIDE','L\'APPARENCE DE LA MAMELLE DE');
insert into suffixes values ('MATIQUE','LE MOUVEMENT DE');
insert into suffixes values ('MERE','COMPOSE DE');
insert into suffixes values ('METRIE','MESURER AVEC');
insert into suffixes values ('MNESIE','LA MEMOIRE DE');
insert into suffixes values ('MORPHE','QUI A LA FORME DE');
insert into suffixes values ('MOTEUR','CONDUIT PAR');
insert into suffixes values ('MYCINE','LE CHAMPIGNON DE');
insert into suffixes values ('MYTHE','LE MYTHE DE');
insert into suffixes values ('NAUTIQUE','NAVIGATION AVEC');
insert into suffixes values ('NEVROSE','LE NERF DE');
insert into suffixes values ('NOMIE','LA LOI DE');
insert into suffixes values ('NUCLEIQUE','QUI CONCERNE LE NOYAU DE');
insert into suffixes values ('ODE','LE CHEMIN DE');
insert into suffixes values ('ODONTE','LA DENT DE');
insert into suffixes values ('OIDE','QUI A LA FORME DE');
insert into suffixes values ('OME','LA TUMEUR DE');
insert into suffixes values ('ONYME','QUI A UN NOM DE');
insert into suffixes values ('OPIE','L\'EXAMEN DE');
insert into suffixes values ('OSE','PRODUIT BASE SUR');
insert into suffixes values ('OURE','QUI A UNE QUEUE DE');
insert into suffixes values ('PARE','QUI ENGENDRE');
insert into suffixes values ('PATHIE','LA MEDECINE DE');
insert into suffixes values ('PEDE','QUI A LES PIEDS DE');
insert into suffixes values ('PITHEQUE','LE SINGE DE');
insert into suffixes values ('PLASME','FACONNE PAR');
insert into suffixes values ('PLASTE','MODELE PAR');
insert into suffixes values ('PNEE','LA RESPIRATION DE');
insert into suffixes values ('PHAGE','QUI MANGE');
insert into suffixes values ('PHILE','QUI AIME');
insert into suffixes values ('PHOBE','QUI CRAINT');
insert into suffixes values ('PHOBIE','QUI A PEUR DE');
insert into suffixes values ('PHONE','QUI A LA VOIX DE');
insert into suffixes values ('PHORE','QUI COMPORTE DE');
insert into suffixes values ('PHTISIE','LE DEPERISSEMENT DE');
insert into suffixes values ('PHYLLE','LA FEUILLE DE');
insert into suffixes values ('PHYSE','LA GLANDE DE');
insert into suffixes values ('PHYTE','QUI NAIT DE');
insert into suffixes values ('POLE','LA VILLE DE');
insert into suffixes values ('PLEGIE','LA PARALYSIE DE');
insert into suffixes values ('PODE','QUI A LE PIED A');
insert into suffixes values ('PTERE','LES AILES DE');
insert into suffixes values ('PUNCTURE','LA PIQURE DE');
insert into suffixes values ('PATHE','LA SOUFFRANCE DE');
insert into suffixes values ('PHYLE','LA TRIBU DE');
insert into suffixes values ('PHRENE','L\'ESPRIT DE');
insert into suffixes values ('PEPTIQUE','QUI CONCERNE LA DIGESTION DE');
insert into suffixes values ('RADIAL','LE RAYON DE');
insert into suffixes values ('RRHEE','L\'ECOULEMENT DE');
insert into suffixes values ('RRAGIE','L\'ECOULEMENT DE');
insert into suffixes values ('RYTHME','LE RYTHME DE');
insert into suffixes values ('SCOPIE','L\'OBSERVATION DE');
insert into suffixes values ('SPHERE','LA SPHERE DE');
insert into suffixes values ('SCAPHE','LA BARQUE DE');
insert into suffixes values ('SOMATIQUE','LE CORPS DE');
insert into suffixes values ('STHESIE','LA SENSIBILITE DE');
insert into suffixes values ('STASE','L\'ARRET DE');
insert into suffixes values ('STROPHE','LE SILLON DE');
insert into suffixes values ('SYNCRASIE','LE TEMPERAMENT DE');
insert into suffixes values ('SYNTHESE','LA SYNTHESE DE');
insert into suffixes values ('STAT','QUI MAINTIENT');
insert into suffixes values ('TAPHE','LE TOMBEAU DE');
insert into suffixes values ('TAXIE','L\'ARRANGEMENT DE');
insert into suffixes values ('TELIE','L\'ELOIGNEMENT DE');
insert into suffixes values ('TECHNIE','LA TECHNIQUE DE');
insert into suffixes values ('THELIAL','LE MAMELON DE');
insert into suffixes values ('THEQUE','LE DEPOT DE');
insert into suffixes values ('THERAPIE','TRAITEMENT D\'UNE MALADIE PAR');
insert into suffixes values ('THERMIQUE','CHALEUR PRODUITE PAR');
insert into suffixes values ('TRON','LE MACHIN DE');
insert into suffixes values ('TROPE','QUI TEND VERS');
insert into suffixes values ('TROPHISME','LA CROISSANCE DE');
insert into suffixes values ('TYPE','LE CARACTERE DE');
insert into suffixes values ('URIE','L\'URINE DE');
insert into suffixes values ('XYLE','LE BOIS DE');
insert into suffixes values ('ZIGOTE','FECONDE PAR');
insert into suffixes values ('ZOAIRE','L\'ANIMAL DE');

grant select on suffixes to public;

